Traceback (most recent call last):
  File "/home/davide/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/davide/.local/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Define parameters for the distributions
mu, sigma = 0., 1.                # Property of Gaussian
a_transl, a_scale  = 1., 2.

transl_v = np.array([ a_transl, 0., a_transl ])
scale_v  = np.array([ 1., a_scale, a_scale ])
mu_v = mu + transl_v
sigma_v = sigma / scale_v

# Create x values for the distributions
x0_plot = np.arange(-4.,4., .05)
p0_norm = norm.pdf(x0_plot, loc=mu, scale=sigma)

xv_plot, pv_norm = [], []
for i in range(len(transl_v)):
    xv_plot += [ x0_plot / scale_v[i] + transl_v[i] ]
    pv_norm += [ norm.pdf(x_plot, loc=mu_v[i], scale=sigma_v[i]) ]
    
# Create subplots
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# Plot
for i in range(len(transl_v)):
    axes[i].plot(x0_plot, p0_norm) #
    axes[i].plot(xv_plot[i], p0_norm*scale_v[i], '--', color='black', lw=2)
    axes[i].plot(x0_plot, pv_norm[i])
    axes[i].set_xlabel("x")
    axes[i].set_ylabel("pdf")
    axes[i].grid()
    axes[i].legend()

# Adjust layout
plt.tight_layout()
plt.show()

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 21[0m
[1;32m     19[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;28mlen[39m(transl_v)):
[1;32m     20[0m     xv_plot [38;5;241m+[39m[38;5;241m=[39m [ x0_plot [38;5;241m/[39m scale_v[i] [38;5;241m+[39m transl_v[i] ]
[0;32m---> 21[0m     pv_norm [38;5;241m+[39m[38;5;241m=[39m [ norm[38;5;241m.[39mpdf([43mx_plot[49m, loc[38;5;241m=[39mmu_v[i], scale[38;5;241m=[39msigma_v[i]) ]
[1;32m     23[0m [38;5;66;03m# Create subplots[39;00m
[1;32m     24[0m fig, axes [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m1[39m, [38;5;241m3[39m, figsize[38;5;241m=[39m([38;5;241m15[39m, [38;5;241m5[39m))

[0;31mNameError[0m: name 'x_plot' is not defined

